Dockerfileのrequirements.txtで自動化
toshima66/notebook-on-docker pull request #1
Opened 2024-11-26 12:20 UTC by hiromichioono

Dockerfileのrequirements.txtで自動化済み

2024-11-26 12:37 UTC, toshima66 requested changes
PRありがとうございます！
いくつくかコメントしたので確認してもらえればと🙏

2024-11-26 12:37 UTC, toshima66 commented on README.md
> +
ここはいらないのでは？

2024-11-26 12:37 UTC, toshima66 commented on docker-compose.yml
> +# version: "3.9"
コメントアウトは不要なので、削除してもらってOKです

2024-11-26 12:37 UTC, toshima66 commented on notebooks/sample.ipynb
> +  {
このファイルは編集しない想定です
編集する場合は、説明を記載してもらえればと思います

2024-12-04 21:02 UTC, hiromichioono commented on notebooks/sample.ipynb
> +  {
追加されたコードは自動生成されたものです。
一度テストで動作確認を行い、表示形式をJupyter公式に合わせました（1行目にコードセルが表示される状態）。

2024-12-10 10:18 UTC, merged

2024-12-10 10:18 UTC, toshima66 commented
@hiromichioono ありがとうございます。マージしました :raised_hands: